{
 "title": "Databases",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "InfluxDB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_tag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "influxdb_metric",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb_producer" }
     ]
    }
   ]
  },
  {
   "title": "Clickhouse",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_tag",
     "database": "default",
     "dateColDataType": "PartitionDate",
     "dateTimeColDataType": "Time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "influxdb_metric",
     "query": "SELECT\n    $timeSeries as t,\n    groupArray((Name, Value)) AS groupArr\nFROM $table\nWHERE $timeFilter\nGROUP BY t, Name\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(Time), 1) * 1) * 1000 as t,     groupArray((Name, Value)) AS groupArr FROM default.metrics WHERE PartitionDate >= toDate(1530024246) AND Time >= toDateTime(1530024246) GROUP BY t, Name ORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": "metrics",
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb_producer" }
     ]
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_tag",
     "expr": "pew",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag" ], "type": "tag" }
     ],
     "legendFormat": "pew",
     "measurement": "influxdb_metric",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "influxdb_producer" }
     ]
    },
    { "expr": "mew", "legendFormat": "mew" },
    { "expr": "dew", "legendFormat": "dew" },
    { "expr": "few", "legendFormat": "few" },
    { "expr": "new", "legendFormat": "new" },
    { "expr": "sew", "legendFormat": "sew" }
   ]
  }
 ]
}